sudo: required
services:
  - docker

# Build the frontend image
before_install:
  - docker build -t signalflowsean/spec-sim -f ./client/Dockerfile.dev ./client

# Run the tests
script:
  - docker run signalflowsean/spec-sim npm test -- --coverage

after_success:
  - docker build -t signalflowsean/spec-sim_client ./client
  - docker build -t signalflowsean/spec-sim_nginx ./nginx
  - docker build -t signalflowsean/spec-sim_server ./api
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push signalflowsean/spec-sim_client
  - docker push signalflowsean/spec-sim_nginx
  - docker push signalflowsean/spec-sim_server
  
# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   env: "SpecSim-env"
#   app: "spec-sim"
#   bucket_name: "elasticbeanstalk-us-east-1-012360740649"
#   bucket_path: "spec-sim"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"