sudo: required
services:
  - docker

before_install:
  - cd frontend
  - docker build -t signalflowsean/spec-sim -f Dockerfile.dev .

script:
  - docker run -e CI=true signalflowsean/spec-sim npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "spec-sim"
  bucket_name: "elasticbeanstalk-us-east-1-012360740649"
  bucket_path: "spec-sim"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"