sudo: required
language: generic
services:
  - docker

before_install:
  - cd frontend
  - docker build -t signalflowsean/spec-sim -f Dockerfile.dev .

script:
  - docker run -e CI=true signalflowsean/spec-sim npm run test