sudo: required
services:
  - docker

# Build the frontend image
before_install:
  - docker build -t signalflowsean/spec-sim -f ./client/Dockerfile.dev ./client

# Run the tests
script:
  - docker run -e CI=true signalflowsean/spec-sim npm test

after_success:
  - docker build -t signalflowsean/spec-sim_client ./client
  - docker build -t signalflowsean/spec-sim_nginx ./nginx
  - docker build -t signalflowsean/spec-sim_server ./api
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push signalflowsean/spec-sim_client
  - docker push signalflowsean/spec-sim_nginx
  - docker push signalflowsean/spec-sim_server

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  env: "SpectralSims-env"
  app: "spectral-sims"
  bucket_name: "elasticbeanstalk-us-east-1-012360740649"
  bucket_path: "spectral-sims"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"