version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /client/node_modules
      - ./client:/cient
  tests:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /client/node_modules
      - ./client:/client
    command: ["npm", "run", "test"]
  server: 
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    # port 5000 from the container mapped to port 5000 on local machine  
    ports: 
      - "5000:5000"
    # volumes mount the cd on the host allowing to listen for changes  
    volumes: 
      - ./server:/server
    environment:  
      FLASK_ENV: development
      S3_KEY: "${S3_KEY}"
      S3_SECRET: "${S3_SECRET}"
      UPLOAD_FOLDER: './uploaded_files_to_s3'

