
version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /opt/www/client/node_modules
      - ./frontend:/opt/www/client
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /opt/www/client/node_modules
      - ./frontend:/opt/www/client
    command: ["npm", "run", "test"]