
version: '3'
services:
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
  tests:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/frontend
    command: ["npm", "run", "test"]