# Python 3.6.7 is the base image in a Alpine linux distrubution
FROM python:3.6.7-alpine3.6

# Author of file.
LABEL maintainer="signalflowsean <signalflowsean@gmail.com>"

# Working directory of the container is /app
WORKDIR '/app'

# Set environment variables used by the flask command
ENV FLASK_APP app.py
ENV FLASK_RUN_HOST 0.0.0.0

# Install gcc so Python packages such as MarkupSafe and SQLAlchemy can compile speedups
RUN apk add --no-cache gcc musl-dev linux-headers

# Copy the list of dependencies to the working directory of the container
COPY requirements.txt .

# update pip
RUN pip install --upgrade pip

# Build the dependencies
RUN pip install -r requirements.txt

# Copy over the rest of the files
# We copy twice to utilize layer caching https://docs.semaphoreci.com/article/81-docker-layer-caching
COPY . . 

# Run the flask app on start
CMD ["flask", "run"]