"""initial migration - Role Users

Revision ID: 29f7a3aa0444
Revises: 
Create Date: 2020-01-18 18:49:42.442832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f7a3aa0444'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usernamewxw', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_usernamewxw'), 'user', ['usernamewxw'], unique=True)
    op.create_table('view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('file_name', sa.String(length=64), nullable=True),
    sa.Column('file_path', sa.String(length=64), nullable=True),
    sa.Column('mfcc_raw', sa.String(length=120), nullable=True),
    sa.Column('mfcc_std_dev', sa.String(length=120), nullable=True),
    sa.Column('mfcc_mean', sa.String(length=120), nullable=True),
    sa.Column('mfcc_avg_diff', sa.String(length=120), nullable=True),
    sa.Column('mfcc_fixed', sa.String(length=120), nullable=True),
    sa.Column('x_corr', sa.String(length=120), nullable=True),
    sa.Column('y_corr', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_view_date_created'), 'view', ['date_created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_view_date_created'), table_name='view')
    op.drop_table('view')
    op.drop_index(op.f('ix_user_usernamewxw'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
