"""users table

Revision ID: 41c50427bf59
Revises: 29f7a3aa0444
Create Date: 2020-01-18 19:02:03.678587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41c50427bf59'
down_revision = '29f7a3aa0444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index('ix_user_usernamewxw', table_name='user')
    op.drop_column('user', 'usernamewxw')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('usernamewxw', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_user_usernamewxw', 'user', ['usernamewxw'], unique=1)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
